//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WithoutPath.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Id { get; set; }
        public int CharacterID { get; set; }
        public int PostID { get; set; }
        public string Content { get; set; }
        public System.DateTime AddedDate { get; set; }
    
        public virtual Character Character { get; set; }
        public virtual Post Post { get; set; }
    }
}
