//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WithoutPath.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Link
    {
        public int Id { get; set; }
        public int FromID { get; set; }
        public int ToID { get; set; }
        public Nullable<int> CharacterID { get; set; }
        public System.DateTime Time { get; set; }
        public int Status { get; set; }
    
        public virtual Character Character { get; set; }
        public virtual SpaceSystem SpaceSystem { get; set; }
        public virtual SpaceSystem SpaceSystem1 { get; set; }
    }
}
