//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WithoutPath.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpaceSystem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SpaceSystem()
        {
            this.Characters = new HashSet<Character>();
            this.Links = new HashSet<Link>();
            this.Links1 = new HashSet<Link>();
            this.SpaceSystemStatics = new HashSet<SpaceSystemStatic>();
        }
    
        public int Id { get; set; }
        public bool IsWormhole { get; set; }
        public Nullable<long> EveID { get; set; }
        public string Name { get; set; }
        public Nullable<double> Security { get; set; }
        public string Note { get; set; }
        public bool IsHome { get; set; }
        public Nullable<int> TypeID { get; set; }
        public Nullable<bool> Warning { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Character> Characters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Link> Links { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Link> Links1 { get; set; }
        public virtual SystemType SystemType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpaceSystemStatic> SpaceSystemStatics { get; set; }
    }
}
