//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WithoutPath.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpaceSystemStatic
    {
        public int Id { get; set; }
        public int SpaceSystemID { get; set; }
        public int StaticsID { get; set; }
    
        public virtual SpaceSystem SpaceSystem { get; set; }
        public virtual Static Static { get; set; }
    }
}
